openapi: 3.0.0
info:
  title: Coffee Catalogue Service API
  version: 1.0.0
paths:
  /health:
    get:
      summary: Get Health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /:
    get:
      summary: Get Coffees
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Coffee'
    post:
      summary: Add new Coffee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCoffee'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Coffee'
  /{coffeeId}:
    get:
      summary: Get Coffee By Id
      parameters:
        - in: path
          name: coffeeId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coffee'
    put:
      summary: Update Coffee By Id
      parameters:
        - in: path
          name: coffeeId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCoffee'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/UpdatedCoffee'
    delete:
      summary: Delete Coffee By Id
      parameters:
        - in: path
          name: coffeeId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: string
components:
  schemas:
    Coffee:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        quantity:
          type: integer
        price:
          type: string
        imageUrl:
          type: string
    NewCoffee:
      type: object
      properties:
        name:
          type: string
        quantity:
          type: integer
        price:
          type: string
        imageUrl:
          type: string
    UpdateCoffee:
      type: object
      properties:
        quantity:
          type: integer
        price:
          type: string
    UpdatedCoffee:
      type: object
      properties:
        quantity:
          type: integer
        price:
          type: string
