apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: esghb-main
      imagePullPolicy: Always
      imageRegistry: docker.io/esghb
      imagePullSecretName: imagepull-docker
      credentialId: credential_64baa799-2095-47da-a26f-9225ded3840b
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: esghb
    version: v1.0.0
    applicationId: app_d480ad1b-b78c-45e9-adef-cf07743cc305
    projectId: project_ced30187-9424-4049-9272-e8dbf6b45fbc
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_08f35a2d-6d8d-4ffc-a53b-5eb0d0765d59
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: esghb
  serviceType: ClusterIP
  version: v1.0.0
  namespace: qa-test-amaan-dev
