apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: ai-repo-driven-main
      imagePullPolicy: Always
      imageRegistry: docker.io/ai-repo-driven
      imagePullSecretName: imagepull-docker
      credentialId: credential_64baa799-2095-47da-a26f-9225ded3840b
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: ai-repo-driven
    version: v1.0.0
    applicationId: app_5e518adc-161a-4bb7-82f3-623a05bbe47c
    projectId: project_ced30187-9424-4049-9272-e8dbf6b45fbc
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_d47a5d19-95bf-4bcc-88d4-ba8a58b020c5
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: ai-repo-driven
  serviceType: ClusterIP
  version: v1.0.0
  namespace: qa-test-amaan-prod
