apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: ai-repo-driven-v1-0-0
    applicationId: app_5e518adc-161a-4bb7-82f3-623a05bbe47c
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_ced30187-9424-4049-9272-e8dbf6b45fbc
    environmentId: env_79a7104f-541a-4007-afdb-98450ca722ce
  name: ai-repo-driven-v1-0-0
spec:
  selector:
    app: ai-repo-driven-v1-0-0
